version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clean_dir.sh
      timeout: 30
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu
