version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
    overwrite: true

permissions:
  - object: /home/ubuntu/app  # 보안상 '/' 전체가 아닌 배포 폴더로 한정해야 합니다.
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755                 # 실행 권한을 명시적으로 부여합니다.

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root             # 프로세스를 죽이는 작업은 root 권한이 가장 확실합니다.
  BeforeInstall:
    - location: scripts/clean_dir.sh
      timeout: 30
      runas: root             # 기존 파일을 삭제하는 작업도 root 권한이 필요합니다.
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ubuntu           # 앱 실행은 일반 사용자 계정으로 진행합니다.